import { boolean, date, integer, pgTable, text, timestamp, unique, index } from "drizzle-orm/pg-core"

export const user = pgTable("user", {
  id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("emailVerified").notNull().default(false), image: text("image"), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow(),
})
export const session = pgTable("session", { id: text("id").primaryKey(), expiresAt: timestamp("expiresAt").notNull(), token: text("token").notNull().unique(), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow(), ipAddress: text("ipAddress"), userAgent: text("userAgent"), userId: text("userId").notNull() })
export const account = pgTable("account", { id: text("id").primaryKey(), accountId: text("accountId").notNull(), providerId: text("providerId").notNull(), userId: text("userId").notNull(), accessToken: text("accessToken"), refreshToken: text("refreshToken"), idToken: text("idToken"), accessTokenExpiresAt: timestamp("accessTokenExpiresAt"), refreshTokenExpiresAt: timestamp("refreshTokenExpiresAt"), scope: text("scope"), password: text("password"), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow() })
export const verification = pgTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expiresAt").notNull(), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow() })

export const gameStats = pgTable("game_stats", { userId: text("userId").primaryKey(), bestScore: integer("bestScore").notNull().default(0), bestCombo: integer("bestCombo").notNull().default(0), totalPerfects: integer("totalPerfects").notNull().default(0), coinsBalance: integer("coinsBalance").notNull().default(50), selectedSkinId: text("selectedSkinId").notNull().default("neon"), region: text("region").notNull().default("US"), streak: integer("streak").notNull().default(0), lastDailyClaim: date("lastDailyClaim"), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow() })
export const gameRuns = pgTable("game_runs", { id: text("id").primaryKey(), userId: text("userId").notNull(), score: integer("score").notNull(), combo: integer("combo").notNull().default(0), perfects: integer("perfects").notNull().default(0), coinsEarned: integer("coinsEarned").notNull().default(0), region: text("region").notNull().default("US"), roomId: text("roomId"), challengeId: text("challengeId"), createdAt: timestamp("createdAt").notNull().defaultNow() }, table => ({ regionScoreIdx: index("game_runs_region_score_idx").on(table.region, table.score), userCreatedIdx: index("game_runs_user_created_idx").on(table.userId, table.createdAt) }))
export const skinPurchases = pgTable("skin_purchases", { id: text("id").primaryKey(), userId: text("userId").notNull(), skinId: text("skinId").notNull(), price: integer("price").notNull(), createdAt: timestamp("createdAt").notNull().defaultNow() }, table => ({ userSkinUnique: unique("skin_purchases_user_skin_unique").on(table.userId, table.skinId) }))
export const multiplayerRooms = pgTable("multiplayer_rooms", { id: text("id").primaryKey(), roomCode: text("roomCode").notNull().unique(), mode: text("mode").notNull(), status: text("status").notNull().default("waiting"), hostUserId: text("hostUserId").notNull(), guestUserId: text("guestUserId"), hostScore: integer("hostScore").notNull().default(0), guestScore: integer("guestScore").notNull().default(0), createdAt: timestamp("createdAt").notNull().defaultNow(), expiresAt: timestamp("expiresAt").notNull() })
export const shareLinks = pgTable("share_links", { id: text("id").primaryKey(), slug: text("slug").notNull().unique(), creatorUserId: text("creatorUserId").notNull(), score: integer("score").notNull().default(0), roomId: text("roomId"), challengeId: text("challengeId"), expiresAt: timestamp("expiresAt").notNull(), createdAt: timestamp("createdAt").notNull().defaultNow() })
