"use server"

import { headers } from "next/headers"
import { and, desc, eq } from "drizzle-orm"
import { auth } from "@/lib/auth"
import { db } from "@/lib/db"
import { gameRuns, gameStats, skinPurchases, user } from "@/lib/db/schema"
import { randomUUID } from "node:crypto"

async function getUserId() { const session = await auth.api.getSession({ headers: await headers() }); if (!session?.user) throw new Error("Unauthorized"); return session.user.id }
export async function getPlayerStats() { const userId = await getUserId(); const rows = await db.select().from(gameStats).where(eq(gameStats.userId, userId)).limit(1); if (rows[0]) return rows[0]; const [created] = await db.insert(gameStats).values({ userId }).returning(); return created }
export async function savePlayerPreferences(input: { region: string; selectedSkinId: string }) { const userId = await getUserId(); await db.insert(gameStats).values({ userId, region: input.region, selectedSkinId: input.selectedSkinId }).onConflictDoUpdate({ target: gameStats.userId, set: { region: input.region, selectedSkinId: input.selectedSkinId, updatedAt: new Date() } }); }
export async function submitGameRun(input: { score: number; combo: number; perfects: number; coinsEarned: number; region: string; roomId?: string; challengeId?: string }) { const userId = await getUserId(); const [stats] = await db.select().from(gameStats).where(eq(gameStats.userId, userId)).limit(1); const [run] = await db.insert(gameRuns).values({ id: randomUUID(), userId, score: Math.max(0, Math.floor(input.score)), combo: Math.max(0, Math.floor(input.combo)), perfects: Math.max(0, Math.floor(input.perfects)), coinsEarned: Math.max(0, Math.floor(input.coinsEarned)), region: input.region, roomId: input.roomId, challengeId: input.challengeId }).returning(); await db.insert(gameStats).values({ userId, region: input.region, bestScore: run.score, bestCombo: run.combo, totalPerfects: run.perfects, coinsBalance: run.coinsEarned }).onConflictDoUpdate({ target: gameStats.userId, set: { region: input.region, bestScore: Math.max(stats?.bestScore ?? 0, run.score), bestCombo: Math.max(stats?.bestCombo ?? 0, run.combo), totalPerfects: (stats?.totalPerfects ?? 0) + run.perfects, coinsBalance: (stats?.coinsBalance ?? 0) + run.coinsEarned, updatedAt: new Date() } }); return run }
export async function getRegionalLeaderboard(region: string) { await getUserId(); return db.select({ id: user.id, name: user.name, score: gameStats.bestScore, combo: gameStats.bestCombo }).from(gameStats).innerJoin(user, eq(gameStats.userId, user.id)).where(eq(gameStats.region, region)).orderBy(desc(gameStats.bestScore)).limit(10) }
export async function purchaseSkin(input: { skinId: string; price: number }) { const userId = await getUserId(); const price = Math.max(0, Math.floor(input.price)); const [stats] = await db.select().from(gameStats).where(eq(gameStats.userId, userId)).limit(1); if (!stats || stats.coinsBalance < price) throw new Error("Not enough coins"); const [owned] = await db.select({ id: skinPurchases.id }).from(skinPurchases).where(and(eq(skinPurchases.userId, userId), eq(skinPurchases.skinId, input.skinId))).limit(1); if (!owned) await db.insert(skinPurchases).values({ id: randomUUID(), userId, skinId: input.skinId, price }); await db.update(gameStats).set({ coinsBalance: stats.coinsBalance - (owned ? 0 : price), selectedSkinId: input.skinId, updatedAt: new Date() }).where(eq(gameStats.userId, userId)); return { skinId: input.skinId, coinsBalance: stats.coinsBalance - (owned ? 0 : price), alreadyOwned: Boolean(owned) } }
