"use server"

import { headers } from "next/headers"
import { eq, or } from "drizzle-orm"
import { randomUUID, randomBytes } from "node:crypto"
import { auth } from "@/lib/auth"
import { db } from "@/lib/db"
import { multiplayerRooms, shareLinks, user as userTable } from "@/lib/db/schema"
import Ably from "ably"

async function userId() { const session = await auth.api.getSession({ headers: await headers() }); if (!session?.user) throw new Error("Unauthorized"); return session.user.id }
async function publishRoomEvent(roomId: string, name: string, data: Record<string, unknown>) { if (!process.env.ABLY_API_KEY) return; const client = new Ably.Rest(process.env.ABLY_API_KEY); await client.channels.get(`stack-rush:${roomId}`).publish(name, data) }
function code() { return randomBytes(3).toString("hex").toUpperCase() }
export async function createRoom(mode: "live" | "async", score = 0) { const hostUserId = await userId(); const roomCode = code(); const id = randomUUID(); await db.insert(multiplayerRooms).values({ id, roomCode, mode, hostUserId, status: "waiting", expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000) }); const slug = randomBytes(8).toString("base64url"); await db.insert(shareLinks).values({ id: randomUUID(), slug, creatorUserId: hostUserId, score, roomId: id, challengeId: mode === "async" ? id : undefined, expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) }); return { roomCode, slug } }
export async function joinRoom(roomCode: string) { const guestUserId = await userId(); const room = await db.select().from(multiplayerRooms).where(eq(multiplayerRooms.roomCode, roomCode.trim().toUpperCase())).limit(1); if (!room[0] || room[0].status !== "waiting") throw new Error("Room unavailable"); await db.update(multiplayerRooms).set({ guestUserId, status: "waiting", hostReady: false, guestReady: false }).where(eq(multiplayerRooms.id, room[0].id)); await publishRoomEvent(room[0].id, "room.joined", { status: "waiting", guestUserId }); return { roomId: room[0].id, mode: room[0].mode } }
export async function getMyRooms() { const id = await userId(); return db.select().from(multiplayerRooms).where(or(eq(multiplayerRooms.hostUserId, id), eq(multiplayerRooms.guestUserId, id))).limit(10) }
export async function getRoomStatus(roomCode: string) { const id = await userId(); const rows = await db.select({ id: multiplayerRooms.id, roomCode: multiplayerRooms.roomCode, mode: multiplayerRooms.mode, status: multiplayerRooms.status, hostScore: multiplayerRooms.hostScore, guestScore: multiplayerRooms.guestScore, hostReady: multiplayerRooms.hostReady, guestReady: multiplayerRooms.guestReady, startAt: multiplayerRooms.startAt, hostFinished: multiplayerRooms.hostFinished, guestFinished: multiplayerRooms.guestFinished, hostUserId: multiplayerRooms.hostUserId, guestUserId: multiplayerRooms.guestUserId }).from(multiplayerRooms).where(eq(multiplayerRooms.roomCode, roomCode.trim().toUpperCase())).limit(1); const room = rows[0]; if (!room || (room.hostUserId !== id && room.guestUserId !== id)) throw new Error("Room unavailable"); const names = await db.select({ id: userTable.id, name: userTable.name }).from(userTable).where(or(eq(userTable.id, room.hostUserId), room.guestUserId ? eq(userTable.id, room.guestUserId) : eq(userTable.id, room.hostUserId))); return { ...room, hostName: names.find((entry) => entry.id === room.hostUserId)?.name ?? "Player 1", guestName: room.guestUserId ? names.find((entry) => entry.id === room.guestUserId)?.name ?? "Player 2" : null } }
export async function setRoomReady(roomId: string) { const id = await userId(); const [room] = await db.select().from(multiplayerRooms).where(eq(multiplayerRooms.id, roomId)).limit(1); if (!room || (room.hostUserId !== id && room.guestUserId !== id)) throw new Error("Room unavailable"); if (!room.guestUserId) throw new Error("Waiting for another player"); const patch = room.hostUserId === id ? { hostReady: true } : { guestReady: true }; const [updated] = await db.update(multiplayerRooms).set(patch).where(eq(multiplayerRooms.id, roomId)).returning(); const ready = Boolean(updated.hostReady && updated.guestReady); if (!ready) { await publishRoomEvent(roomId, "player.ready", { status: "ready", userId: id }); return updated } const startAt = new Date(Date.now() + 3000); const [started] = await db.update(multiplayerRooms).set({ status: "countdown", startAt }).where(eq(multiplayerRooms.id, roomId)).returning(); await publishRoomEvent(roomId, "match.countdown", { status: "countdown", startAt: startAt.toISOString(), countdownMs: 3000 }); return started }
function safeScore(score: number) { return Math.min(1000000, Math.max(0, Math.floor(Number(score) || 0))) }
export async function updateRoomScore(roomId: string, score: number) { const id = await userId(); const [room] = await db.select().from(multiplayerRooms).where(eq(multiplayerRooms.id, roomId)).limit(1); if (!room || (room.hostUserId !== id && room.guestUserId !== id) || !["countdown", "playing"].includes(room.status)) throw new Error("Room unavailable"); const value = safeScore(score); const side = room.hostUserId === id ? "host" : "guest"; await db.update(multiplayerRooms).set(side === "host" ? { hostScore: value } : { guestScore: value }).where(eq(multiplayerRooms.id, roomId)); await publishRoomEvent(roomId, "score.updated", { score: value, side }); return { ok: true, score: value, side } }
async function roomPlayerNames(room: { hostUserId: string; guestUserId: string | null }) { const names = await db.select({ id: userTable.id, name: userTable.name }).from(userTable).where(or(eq(userTable.id, room.hostUserId), room.guestUserId ? eq(userTable.id, room.guestUserId) : eq(userTable.id, room.hostUserId))); return { hostName: names.find((entry) => entry.id === room.hostUserId)?.name ?? "Player 1", guestName: room.guestUserId ? names.find((entry) => entry.id === room.guestUserId)?.name ?? "Player 2" : null } }
export async function finishRoom(roomId: string, score: number) { const id = await userId(); const [room] = await db.select().from(multiplayerRooms).where(eq(multiplayerRooms.id, roomId)).limit(1); if (!room || (room.hostUserId !== id && room.guestUserId !== id) || !["countdown", "playing"].includes(room.status)) throw new Error("Room unavailable"); const value = safeScore(score); const side = room.hostUserId === id ? "host" : "guest"; const patch = side === "host" ? { hostScore: value, hostFinished: true } : { guestScore: value, guestFinished: true }; await db.update(multiplayerRooms).set(patch).where(eq(multiplayerRooms.id, roomId)); const [updated] = await db.select().from(multiplayerRooms).where(eq(multiplayerRooms.id, roomId)).limit(1); if (!updated.hostFinished || !updated.guestFinished) { await publishRoomEvent(roomId, "player.finished", { side, score: value }); let latest = updated; for (let attempt = 0; attempt < 20 && !(latest.hostFinished && latest.guestFinished); attempt += 1) { await new Promise((resolve) => setTimeout(resolve, 500)); const [next] = await db.select().from(multiplayerRooms).where(eq(multiplayerRooms.id, roomId)).limit(1); if (next) latest = next } if (!(latest.hostFinished && latest.guestFinished)) return { status: latest.status, winner: null, hostScore: latest.hostScore, guestScore: latest.guestScore, ...(await roomPlayerNames(latest)) }; return { status: "finished", winner: latest.hostScore === latest.guestScore ? "draw" : latest.hostScore > latest.guestScore ? "host" : "guest", hostScore: latest.hostScore, guestScore: latest.guestScore, ...(await roomPlayerNames(latest)) } } const winner = updated.hostScore === updated.guestScore ? "draw" : updated.hostScore > updated.guestScore ? "host" : "guest"; await db.update(multiplayerRooms).set({ status: "finished" }).where(eq(multiplayerRooms.id, roomId)); await publishRoomEvent(roomId, "match.finished", { status: "finished", hostScore: updated.hostScore, guestScore: updated.guestScore, winner }); return { status: "finished", winner, hostScore: updated.hostScore, guestScore: updated.guestScore, ...(await roomPlayerNames(updated)) } }
export async function leaveRoom(roomId: string) { const id = await userId(); const [room] = await db.select().from(multiplayerRooms).where(eq(multiplayerRooms.id, roomId)).limit(1); if (!room || (room.hostUserId !== id && room.guestUserId !== id)) throw new Error("Room unavailable"); await db.update(multiplayerRooms).set({ status: "abandoned" }).where(eq(multiplayerRooms.id, roomId)); await publishRoomEvent(roomId, "room.abandoned", { status: "abandoned", userId: id }); return { ok: true } }
export async function rematchRoom(roomId: string) { const id = await userId(); const [room] = await db.select().from(multiplayerRooms).where(eq(multiplayerRooms.id, roomId)).limit(1); if (!room || (room.hostUserId !== id && room.guestUserId !== id)) throw new Error("Room unavailable"); await db.update(multiplayerRooms).set({ status: "ready", hostScore: 0, guestScore: 0, hostReady: false, guestReady: false, startAt: null, hostFinished: false, guestFinished: false }).where(eq(multiplayerRooms.id, roomId)); await publishRoomEvent(roomId, "match.rematch", { status: "ready" }); return { ok: true } }
export async function submitChallengeResult(slug: string, score: number) { const id = await userId(); const link = await db.select().from(shareLinks).where(eq(shareLinks.slug, slug)).limit(1); if (!link[0] || link[0].expiresAt < new Date()) throw new Error("Challenge expired"); const value = Math.max(0, Math.floor(score)); if (link[0].roomId) await updateRoomScore(link[0].roomId, value); return { creatorScore: link[0].score, score: value, won: value > link[0].score, userId: id } }
