"use client"

import { ArrowLeft, Check, Lock, Trophy } from "lucide-react"
import { ACHIEVEMENTS, achievementProgress } from "@/lib/achievements"
import type { GameStorage } from "@/hooks/use-game-storage"

export function AchievementsScreen({ storage, onBack }: { storage: GameStorage; onBack: () => void }) {
  return <main className="min-h-[100dvh] bg-slate-950 px-5 py-6 text-white"><header className="mx-auto flex w-full max-w-lg items-center gap-4"><button onClick={onBack} aria-label="Back" className="rounded-full bg-white/10 p-2"><ArrowLeft size={18} /></button><div><p className="font-mono text-xs uppercase tracking-[0.25em] text-cyan-300">Progress</p><h1 className="text-2xl font-bold">Achievements</h1></div></header><section className="mx-auto mt-7 grid w-full max-w-lg gap-3">{ACHIEVEMENTS.map((achievement) => { const progress = achievementProgress(achievement, storage); const completed = progress >= achievement.target; const claimed = storage.claimedAchievements.includes(achievement.id); return <article key={achievement.id} className="rounded-2xl border border-white/10 bg-white/[0.06] p-4"><div className="flex items-start gap-3"><div className={`rounded-xl p-3 ${completed ? "bg-cyan-300 text-slate-950" : "bg-white/10 text-white/60"}`}>{completed ? <Check size={20} /> : <Trophy size={20} />}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><h2 className="font-semibold">{achievement.title}</h2><span className="text-xs font-semibold text-amber-300">+{achievement.reward} coins</span></div><p className="mt-1 text-sm text-white/60">{achievement.description}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-cyan-300 transition-all" style={{ width: `${(progress / achievement.target) * 100}%` }} /></div><p className="mt-2 text-xs text-white/45">{progress}/{achievement.target}{claimed ? " · Reward claimed" : completed ? " · Complete" : ""}</p></div>{!completed && <Lock size={15} className="text-white/30" />}</div></article> })}</section></main>
}
